---
- name: ping server
  ping:

- name: Update apt cache
  apt:
    update_cache: yes

- name: Install gnupg, apt-transport-https
  apt:
    name:
      - apt-transport-https
      - gnupg
    state: present

- name: Copy elasticsearch-7.17.16-amd64.deb
  copy:
    src: elasticsearch-7.17.16-amd64.deb
    dest: /home/user/

- name: Install elasticsearch
  apt:
    deb: /home/user/elasticsearch-7.17.16-amd64.deb

- name: Copy config file for elasticsearch
  copy:
    src: elasticsearch.yml
    dest: /etc/elasticsearch
    mode: 0644
    owner: user
    group: root

- name: enable and restart elasticsearch
  ansible.builtin.systemd:
    name: elasticsearch
    enabled: true
    masked: no
    state: restarted
